version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        container_name: db_pet-diet
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=
            - MYSQL_USER=
        ports:
            - '8002:3306'

    webserver:
        image: 'nginx:alpine'
        restart: always
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - mysql
        ports:
            - '8000:80'

    php-fpm:
        build: 
          context: .
          dockerfile: Dockerfile
        container_name: php
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'